server:
  port: 8000

spring:
  cloud:
    gateway:
      webmvc:
        routes:
          - id: ms2_userservice
            uri: lb://ms2_userservice
            predicates:
              - path=/user/**
          - id: ms2_notesservice
            uri: lb://ms2_notesservice
            predicates:
              - path=/notes/**